---
# tasks file for mysql_installation

- name: firewall config
  include: firewall_config.yml
  when:
    - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'


- name: Mysql Installtion
  include: mysql_setup.yml
  when: 
    - ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'
